services:
  flavourvault-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DbConnectionString=${DB_ConnectionString}
      - ConnectionStrings__AzureServiceBusConnectionString=${ASB_ConnectionString}
      - MessageBus__Topics=Notification
    ports:
      - 5000:8080
      - 5001:8081 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro