#docker network create local_dev
#docker compose up -d
#docker-compose config (Command to validate file)

networks:
  local_dev:
    external: true
  
services:
  flavourvault-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    container_name: flavourvault-db
    hostname: flavourvault-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - 14330:1433
    volumes:
      - ./flavourvault-db/backups:/var/opt/mssql/backups
      - ./flavourvault-db/data:/var/opt/mssql/data
      - ./flavourvault-db/log:/var/opt/mssql/log
    networks:
        - local_dev
  flavourvault-azureservicebus:
    container_name: "flavourvault-azureservicebus"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: flavourvault-db  
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      flavourvault-db:
        condition: service_started 
    networks:
        - local_dev
  flavourvault-rabbitmq:
    image: rabbitmq:4-management
    container_name: flavourvault-rabbitmq
    ports:
      - 5671:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
        - local_dev
  flavourvault-service:
    image: ${DOCKER_REGISTRY-}flavourvault-service
    build:
      context: .
      dockerfile: FlavourVault.Web/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081
    networks:
        - local_dev
    depends_on:
      flavourvault-db:
        condition: service_started 
      flavourvault-azureservicebus:
        condition: service_started
      flavourvault-rabbitmq:
        condition: service_started  
  
  